# Project
mod_version=21.4.0
maven_group=com.unrealdinnerbone
curse_id=517003
mod_name=JAGS
mod_author=UnRealDinnerbone
mod_id=jags


# Common
minecraft_version=1.21.4

# Forge
#forge_version=49.0.13

neo_version=21.4.12-beta

fabric_version=0.111.0+1.21.4
fabric_loader_version=0.16.9

# Other
trenzalore_version=21.4.2

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false