# Project
mod_version=26.1.0.1
maven_group=com.unrealdinnerbone
curse_id=517003
mod_name=JAGS
mod_author=UnRealDinnerbone
mod_id=jags

# Common
minecraft_version=26.1

neo_version=26.1.0.1-beta

fabric_version=0.144.0+26.1
fabric_loader_version=0.18.4

trenzalore_version=26.1.0.1

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false